### ISSUE TITLE
重连cqhttp失败，程序直接退出

### ISSUE THREAD

**Issue by cc004** [Hoshikawa-Kaguya/Sora#38]
**使用环境**
 -  框架版本号:`0.9.9`
 -  运行环境:`winserver 2016 go-cqhttp v1.0.0 beta5`

**bug描述**
重连go-cqhttp会失败并进程直接退出，必须先启动bot再启动go-cqhttp才能避免

**如何复现**
1. 开启bot
2. 开启cqhttp
3. 关闭bot
4. 开启bot

**错误截图或日志**
### 第一次：
[2021/8/29 20:26:22][ERROR][Sora]与Onebot客户端[127.0.0.1:49415]失去链接(心跳包超时)
[2021/8/29 20:26:22][ERROR][Sora]与Onebot客户端[127.0.0.1:49420]失去链接(心跳包超时)
[2021/8/29 20:26:22][ERROR][Sora]与Onebot客户端[127.0.0.1:49423]失去链接(心跳包超时)
[2021/8/29 20:26:22][FATAL][Sora]Websocket连接被关闭失败
[2021/8/29 20:26:22][FATAL][Sora]Websocket连接被关闭失败
[2021/8/29 20:26:22][FATAL][Sora]Websocket连接被关闭失败
[2021/8/29 20:26:22][WARNINIG][Sora]将在5s后自动退出
[2021/8/29 20:26:22][WARNINIG][Sora]将在5s后自动退出
[2021/8/29 20:26:22][WARNINIG][Sora]将在5s后自动退出

### 第二次：

[2021/8/29 20:28:47][ERROR][Sora]与Onebot客户端[127.0.0.1:49607]失去链接(心跳包超时)
[2021/8/29 20:28:47][ERROR][Sora]与Onebot客户端[127.0.0.1:49610]失去链接(心跳包超时)
[2021/8/29 20:28:47][ERROR][Sora]与Onebot客户端[127.0.0.1:49613]失去链接(心跳包超时)
[2021/8/29 20:28:47][ERROR][Sora]与Onebot客户端[127.0.0.1:49615]失去链接(心跳包超时)
[2021/8/29 20:28:47][ERROR][Sora]与Onebot客户端[127.0.0.1:49619]失去链接(心跳包超时)
[2021/8/29 20:28:47][ERROR][Sora]与Onebot客户端[127.0.0.1:49621]失去链接(心跳包超时)
[2021/8/29 20:28:47][INFO][Sora]客户端连接被关闭[127.0.0.1:49613]
[2021/8/29 20:28:47][INFO][Sora]客户端连接被关闭[127.0.0.1:49615]
[2021/8/29 20:28:47][INFO][Sora]客户端连接被关闭[127.0.0.1:49619]
[2021/8/29 20:28:47][INFO][Sora]客户端连接被关闭[127.0.0.1:49621]
[2021/8/29 20:28:47][ERROR][Sora]检查心跳包时发生错误 code -1, 连接[94f9fdde-9fe1-412c-851a-d9f156538d01]无法被关闭
FATAL][Sora]Websocket连接被关闭失败
[2021/8/29 20:28:47][FATAL][Sora]Websocket连接被关闭失败
[2021/8/29 20:28:47][ERROR][Sora]检查心跳包时发生错误 code -1, 连接[3704197d-d7dc-48c1-ad7f-8c131f21b5b5]无法被关闭
[2021/8/29 20:28:47][WARNINIG][Sora]将在5s后自动退出
[2021/8/29 20:28:47][WARNINIG][Sora]将在5s后自动退出
[2021/8/29 20:28:47][ERROR][Sora]检查心跳包时发生错误 code -1, 连接[895c40c8-e359-4111-8726-885f60cb5eb6]无法被关闭
[2021/8/29 20:28:47][ERROR][Sora]检查心跳包时发生错误 code -1, 连接[c977ebcd-909b-4348-a7c9-de01a263fe0d]无法被关闭
[2021/8/29 20:28:47][INFO][Sora]已连接客户端[127.0.0.1:49643]
[2021/8/29 20:28:47][INFO][Sora]已连接到go-cqhttp,版本:v1.0.0-beta5

**Comment by Yukari316** [comment]
是一次开了多个`gocq`么
能否发一下`gocq`的配置文件（从现有的报错来看只能推测是心跳包的问题）
以及就是现有的log能给出的信息较少，请将log的等级调整为`DEBUG`

**Comment by cc004** [comment]
单个gocq
```yml
# go-cqhttp 默认配置文件

account: # 账号相关
  uin: # QQ账号
  password: '' # 密码为空时使用扫码登录
  encrypt: false  # 是否开启密码加密
  status: 0      # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  relogin: # 重连设置
    delay: 3   # 首次重连延迟, 单位秒
    interval: 3   # 重连间隔
    max-times: 0  # 最大重连次数, 0为无限制

  # 是否使用服务器下发的新地址进行重连
  # 注意, 此设置可能导致在海外服务器上连接情况更差
  use-sso-address: true

heartbeat:
  # 心跳频率, 单位秒
  # -1 为关闭心跳
  interval: 5

message:
  # 上报数据类型
  # 可选: string,array
  post-format: array
  # 是否忽略无效的CQ码, 如果为假将原样发送
  ignore-invalid-cqcode: false
  # 是否强制分片发送消息
  # 分片发送将会带来更快的速度
  # 但是兼容性会有些问题
  force-fragment: true
  # 是否将url分片发送
  fix-url: false
  # 下载图片等请求网络代理
  proxy-rewrite: ''
  # 是否上报自身消息
  report-self-message: false
  # 移除服务端的Reply附带的At
  remove-reply-at: false
  # 为Reply附加更多信息
  extra-reply-data: false
  # 跳过 Mime 扫描, 忽略错误数据
  skip-mime-scan: false

output:
  # 日志等级 trace,debug,info,warn,error
  log-level: warn
  # 日志时效 单位天. 超过这个时间之前的日志将会被自动删除. 设置为 0 表示永久保留.
  log-aging: 15
  # 是否在每次启动时强制创建全新的文件储存日志. 为 false 的情况下将会在上次启动时创建的日志文件续写
  log-force-new: true
  # 是否启用 DEBUG
  debug: false # 开启调试模式

# 默认中间件锚点
default-middlewares: &default
  # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: ''
  # 事件过滤器文件目录
  filter: ''
  # API限速设置
  # 该设置为全局生效
  # 原 cqhttp 虽然启用了 rate_limit 后缀, 但是基本没插件适配
  # 目前该限速设置为令牌桶算法, 请参考:
  # https://baike.baidu.com/item/%E4%BB%A4%E7%89%8C%E6%A1%B6%E7%AE%97%E6%B3%95/6597000?fr=aladdin
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1  # 令牌回复频率, 单位秒
    bucket: 1     # 令牌桶大小

database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true

# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器
  # 反向WS设置
  - ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://localhost:6700
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```
